name: PR Source Code Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.1'
          cache: 'yarn'
      - run: yarn
      - run: yarn lint:strict

  tsc:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.1'
          cache: 'yarn'
      - run: yarn
      - run: yarn typecheck

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.1'
          cache: 'yarn'
      - run: yarn
      - run: yarn format:check

  # test:
  #   name: Run Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.18.1'
  #         cache: 'yarn'
  #     - run: yarn
  #     - run: yarn test
